version: "3.5"

services:
  media:
    image: cincarnato/ci-media
    container_name: ci_media
    volumes:
      - ./media:/apps/api/dist/media
      - ./logs:/apps/api/dist/logs
      - ./.env:/apps/api/dist/.env
    ports:
      - "80:5000"
    networks:
      - "host"
